const { colors, typography, spacing } = require('./src/theme');

module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: colors.primary,
        secondary: colors.secondary,
        text: colors.text,
        background: colors.background,
        border: colors.border,
        success: colors.success,
        error: colors.error,
        warning: colors.warning,
      },
      fontFamily: typography.fontFamily,
      fontSize: {
        'xs-mobile': typography.fontSize.xs.mobile,
        'sm-mobile': typography.fontSize.sm.mobile,
        'base-mobile': typography.fontSize.base.mobile,
        'lg-mobile': typography.fontSize.lg.mobile,
        'xl-mobile': typography.fontSize.xl.mobile,
        '2xl-mobile': typography.fontSize['2xl'].mobile,
        '3xl-mobile': typography.fontSize['3xl'].mobile,
        '4xl-mobile': typography.fontSize['4xl'].mobile,
        '5xl-mobile': typography.fontSize['5xl'].mobile,
        
        'xs-tablet': typography.fontSize.xs.tablet,
        'sm-tablet': typography.fontSize.sm.tablet,
        'base-tablet': typography.fontSize.base.tablet,
        'lg-tablet': typography.fontSize.lg.tablet,
        'xl-tablet': typography.fontSize.xl.tablet,
        '2xl-tablet': typography.fontSize['2xl'].tablet,
        '3xl-tablet': typography.fontSize['3xl'].tablet,
        '4xl-tablet': typography.fontSize['4xl'].tablet,
        '5xl-tablet': typography.fontSize['5xl'].tablet,
        
        'xs-desktop': typography.fontSize.xs.desktop,
        'sm-desktop': typography.fontSize.sm.desktop,
        'base-desktop': typography.fontSize.base.desktop,
        'lg-desktop': typography.fontSize.lg.desktop,
        'xl-desktop': typography.fontSize.xl.desktop,
        '2xl-desktop': typography.fontSize['2xl'].desktop,
        '3xl-desktop': typography.fontSize['3xl'].desktop,
        '4xl-desktop': typography.fontSize['4xl'].desktop,
        '5xl-desktop': typography.fontSize['5xl'].desktop,
      },
      fontWeight: typography.fontWeight,
      lineHeight: typography.lineHeight,
      letterSpacing: typography.letterSpacing,
      spacing: spacing,
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [],
};